filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Hamish, Welcome to Coot version 0.8.9-pre")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\WinCoot\share\coot\data\tutorial-modern.pdb", 1)
make_and_draw_map ("C:\WinCoot\share\coot\data\rnasa-1.8-all_refmac1.mtz", "FWT", "PHWT", "", 0, 0)
make_and_draw_map ("C:\WinCoot\share\coot\data\rnasa-1.8-all_refmac1.mtz", "DELFWT", "PHDELWT", "", 0, 1)
